apiVersion: v1
kind: ConfigMap
metadata:
  name: h2console-cm
data:
  # property-like keys; each key maps to a simple value
  DATABASE_URL: "jdbc:h2:file:~/products;AUTO_SERVER=true"
  DATABASE_USERNAME: root