
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  call-build:
    uses: vantru/shared-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: userservice
      context: .
    secrets: inherit
  update-k8s:
    needs:
      - call-build
      # - scan
    runs-on: ubuntu-latest
     
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Debug workspace
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          pwd
          ls -la
          ls -la k8s || true
          find . -maxdepth 3 -type f
      - name: install yq
        uses: mikefarah/yq@v4.44.3
      - name: Update Kubernetes manifest
        run: |
          FILE=./k8s/orderservice-pod.yml
          yq -i '.spec.template.spec.containers[0].image = "hardingtrutran/ordersservice:${{ needs.build.outputs.short_sha }}"' "$FILE"
          cat "$FILE"
      - name: commit deployment ordersservice file change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@noreply"
          git add k8s/orderservice-pod.yml
          git commit -m "change tag sha"
          git push origin main
